services:
    rabbitmq1:
        image: rabbitmq:3.8-management
        networks:
            - rabbits
        volumes:
            - ./configfile/:/config/
            # - ./homedir/:/var/lib/rabbitmq/
        env_file: .env   
        hostname: rabbit-1
        container_name: rabbit-1
        ports:
            - 8081:15672
            - 5672:5672
    rabbitmq2:
        networks:
            - rabbits
        volumes:
            - ./configfile/:/config/
        env_file: .env   
        hostname: rabbit-2
        container_name: rabbit-2
        ports:
            - 8082:15672
        image: rabbitmq:3.8-management
    
    rabbitmq3:
        networks:
            - rabbits
        volumes:
            - ./configfile/:/config/
        env_file: .env   
        hostname: rabbit-3
        container_name: rabbit-3
        ports:
            - 8083:15672
        image: rabbitmq:3.8-management

networks:
    rabbits:
        external: true
        name: rabbits